[versions]
kotlin = "1.9.0"
kotest = "5.7.2"
ktor = "2.3.5"

# ANDROID
androidCompileSdk = "33"
androidGradlePlugin = "8.1.0"
androidMinSdk = "21"
androidTargetSdk = "33"

# JVM
jvmVersion = "11"

# LINT
detekt = "1.23.1"

[libraries]
# NETWORKING
json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.6.0" }
ktorEngine = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktorClient = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorLogging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

[plugins]
androidGradlePlugin = { id = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }