package metal.diary.app

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFF6750A4)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF21005D)
val md_theme_light_secondary = Color(color = 0xFF625B71)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF1D192B)
val md_theme_light_tertiary = Color(color = 0xFF7D5260)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF31111D)
val md_theme_light_error = Color(color = 0xFFB3261E)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_errorContainer = Color(color = 0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(color = 0xFF410E0B)
val md_theme_light_outline = Color(color = 0xFF79747E)
val md_theme_light_background = Color(color = 0xFFFFFBFE)
val md_theme_light_onBackground = Color(color = 0xFF1C1B1F)
val md_theme_light_surface = Color(color = 0xFFFFFBFE)
val md_theme_light_onSurface = Color(color = 0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(color = 0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF49454F)
val md_theme_light_inverseSurface = Color(color = 0xFF313033)
val md_theme_light_inverseOnSurface = Color(color = 0xFFF4EFF4)
val md_theme_light_inversePrimary = Color(color = 0xFFD0BCFF)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFF6750A4)
val md_theme_light_outlineVariant = Color(color = 0xFFCAC4D0)
val md_theme_light_scrim = Color(color = 0xFF000000)

val md_theme_dark_primary = Color(color = 0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(color = 0xFF381E72)
val md_theme_dark_primaryContainer = Color(color = 0xFF4F378B)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFFEADDFF)
val md_theme_dark_secondary = Color(color = 0xFFCCC2DC)
val md_theme_dark_onSecondary = Color(color = 0xFF332D41)
val md_theme_dark_secondaryContainer = Color(color = 0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFFE8DEF8)
val md_theme_dark_tertiary = Color(color = 0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(color = 0xFF492532)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFFFFD8E4)
val md_theme_dark_error = Color(color = 0xFFF2B8B5)
val md_theme_dark_onError = Color(color = 0xFF601410)
val md_theme_dark_errorContainer = Color(color = 0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(color = 0xFFF9DEDC)
val md_theme_dark_outline = Color(color = 0xFF938F99)
val md_theme_dark_background = Color(color = 0xFF1C1B1F)
val md_theme_dark_onBackground = Color(color = 0xFFE6E1E5)
val md_theme_dark_surface = Color(color = 0xFF1C1B1F)
val md_theme_dark_onSurface = Color(color = 0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(color = 0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFCAC4D0)
val md_theme_dark_inverseSurface = Color(color = 0xFFE6E1E5)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF313033)
val md_theme_dark_inversePrimary = Color(color = 0xFF6750A4)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(color = 0xFF49454F)
val md_theme_dark_scrim = Color(color = 0xFF000000)

val seed = Color(color = 0xFF6750A4)
